CREATE TABLE `t_user_comments` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`content_id` VARCHAR(50) NOT NULL,
	`type` INT(10) NOT NULL,
	`title` VARCHAR(50) NULL DEFAULT NULL,
	`content` VARCHAR(255) NULL DEFAULT NULL,
	`add_time` INT(50) NULL DEFAULT NULL,
	`hot` INT(50) NULL DEFAULT NULL,
	`playTime` VARCHAR(10) NULL DEFAULT NULL,
	`keywords` VARCHAR(255) NULL DEFAULT NULL,
	`star_info` VARCHAR(255) NULL DEFAULT NULL,
	`related_star` VARCHAR(255) NULL DEFAULT NULL,
	`uid` VARCHAR(255) NULL DEFAULT NULL,
	`suid` VARCHAR(255) NULL DEFAULT NULL,
	`uname` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
